version: '3'

networks:
  test_network:
    driver: bridge

volumes:
  postgresql_storage:


services:
  redis:
    image: redis:latest
    container_name: redis_url
    ports:
      - "6379:6379"
    networks:
      - test_network
    restart: on-failure:5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  postgresql:
    image: postgres:latest
    container_name: postgres_url
    ports:
      - "5433:5433"
    networks:
      - test_network
    volumes:
      - postgresql_storage:/data
    restart: on-failure:5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sourav404
      POSTGRES_DB: URL_Shortner
